### ISSUE TITLE
State resets when app fast refreshes 

### ISSUE THREAD

**Issue by emadabdulrahim** [esetnik/customize-cra-react-refresh#1]
States resets whenever app refreshes for a text change or anything at all. 

Steps I followed
1. `npx create-react-app`
2. install dependencies listed on the readme here
3. add `config-overrides.js` on the root level
4. copy example code from the readme
5. Created a simple counter state and seeing the states resets whenever I change any text on any component.

What am I missing?

**Comment by esetnik** [comment]
@emadabdulrahim sorry you had trouble. Is this your first time using `react-app-rewired`? If so, you'll need to [follow instructions to run `react-app-rewired` instead of `react-scripts`](https://github.com/timarney/react-app-rewired#3-flip-the-existing-calls-to-react-scripts-in-npm-scripts-for-start-build-and-test) otherwise the injections won't be applied.

#### 3) 'Flip' the existing calls to `react-scripts` in `npm` scripts for start, build and test
```diff
  /* package.json */

  "scripts": {
-   "start": "react-scripts start",
+   "start": "react-app-rewired start",
-   "build": "react-scripts build",
+   "build": "react-app-rewired build",
-   "test": "react-scripts test --env=jsdom",
+   "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject"
}
```

**Comment by emadabdulrahim** [comment]
Right, I totally forgot. Thanks!

**Comment by esetnik** [comment]
@emadabdulrahim I'll update the readme to include that in the list of instructions.
